# _config.yml
title: "Boris Benedikter, Ph.D."
subtitle: "Postdoc in Aerospace Autonomy, Optimal Control, and AI"
author: "Boris Benedikter"
description: "Official website of Boris Benedikter, a postdoctoral researcher at the University of Arizona specializing in trustworthy aerospace autonomy, real-time guidance, optimal control, and machine learning. Explore my research, publications, and teaching philosophy."

plugins:
  - jekyll-scholar
  - jekyll-sitemap

url: "https://www.borisbenedikter.com"

scholar:
  # style: apa
  # style: ieee
  style: "_bibliography/apa-custom.csl"
  locale: en
  bibliography_template: "{{ reference | replace_first: 'Benedikter, B.', '<b>Benedikter, B.</b>' }}"

  sort_by: [year, month]
  order: descending

  highlight_authors: ['Benedikter, B.', 'Benedikter, Boris', 'B. Benedikter', 'Boris Benedikter']

  source: ./_bibliography/
  bibliography: references.bib

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"